name: Pipeline Principal

on:
  push:
  workflow_dispatch:

jobs:
  setup-e-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem inicial
        run: echo "Analisando qualidade do código..."

  testes-unitarios:
    runs-on: ubuntu-latest
    needs: setup-e-lint    # Job 2 depende do Job 1
    steps:
      - name: Testes
        run: echo "Rodando testes unitários..."

  scan-de-seguranca:
    runs-on: ubuntu-latest
    needs: setup-e-lint    # Job 3 também depende do Job 1
    steps:
      - name: Segurança
        run: echo "Procurando vulnerabilidades..."
