name: Pipeline com Testes

on:
  push:
  workflow_dispatch:

jobs:
  setup-e-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem inicial
        run: echo "Analisando qualidade do código..."

  testes-unitarios:
    runs-on: ubuntu-latest
    needs: setup-e-lint   # Job 2 depende do Job 1
    steps:
      - name: Rodando testes
        run: echo "Rodando testes unitários..."
